server:
  port: 8000
  
spring:
  application:
    name: consul-order

  cloud:
    consul:
      host: 192.168.1.215
      port: 8500
      discovery:
        hostname: 192.168.1.215
        health-check-path: /actuator/health 
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}


