##会员服务端口
server:
  port: 8001
  
spring:
  application:
    name: order-consumer
  profiles: order1
  
eureka:
  instance:
    hostname: order1
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/ 
      
ribbon:
# 设置建立连接的时间
  ReadTimeout: 5000
  #设置连接后返回资源的时间
  ConnectTimeout: 5000

---

server:
  port: 8002
  
spring:
  application:
    name: order-consumer
  profiles: order2
  
eureka:
  instance:
    hostname: order2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/ 