server:
  port: 8082
  
spring:
  application:
    name: consul-member

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        health-check-path: /actuator/health 
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
        

