##会员服务端口
server:
  port: 8001
  
spring:
  application:
    name: order
  profiles: order1
  
eureka:
  instance:
    hostname: order1
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/ 

---
server:
  port: 8002
  
spring:
  application:
    name: order
  profiles: order2
  
eureka:
  instance:
    hostname: order2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/ 

---

server:
  port: 8003
  
spring:
  application:
    name: order
  profiles: order3
  
eureka:
  instance:
    hostname: order3
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/ 

      