server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles: eureka1

eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    hostname: eureka1

---

server:
  port: 8762

spring:
  application:
    name: eureka-server
  profiles: eureka2

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
  instance:
    hostname: eureka2    

---

server:
  port: 8763

spring:
  application:
    name: eureka-server
  profiles: eureka3

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    hostname: eureka3
    