eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/



spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chstdsj/springcloud
          search-paths: spring-cloud
  application:
    name: config-server

server:
  port: 8888
